FROM golang:1.22 as builder

ENV HOME /app
ENV CGO_ENABLED 0
ENV GOOS linux
ENV GOPROXY=direct

WORKDIR /app


RUN export PATH=$PATH:/usr/local/go/bin/sh

COPY go.mod go.sum ./

RUN go get gorm.io/gorm
RUN go get gorm.io/driver/postgres

RUN go mod tidy
COPY . .

RUN go build -a -installsuffix cgo -o main .

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/main .

RUN apk add --no-cache inotify-tools

EXPOSE 8080

RUN chmod +x main

CMD ["./main"]